### ISSUE TITLE
Page crashes

### ISSUE THREAD

**Issue by ollicle** [fxsitecompat/firefox-extension#1]
Today I was struck with a couple of page crashes in Firefox. After the second page crashed (on a familiar website) it occurred to me to disable some add-ons. Remembering I had provided fresh permissions to this add-on this morning (version 2.2.3) I tried disabling it first and the crashes ceased.

I’m using Firefox developer edition on a Mac running MacOS 10.13.6

This was page was crashing every time on load until I disabled this add-on:
https://www.beyondbank.com.au/personal-banking.html

I can provide further info if it helps.

**Comment by kyoshino** [comment]
Hi @ollicle,

I just created a fresh Firefox user profile, installed version 2.2.3, and visited the website, but couldn’t reproduce the issue.

Actually I have released version 2.2.4 to improve performance. Can you please update your add-on to see if crashes still happen?

If so, please submit a crash report to Mozilla, and let me know the report ID that can be found by entering `about:crashes` to the location bar. I see you’re using an older version of macOS (mine is 10.15.4), which might be perhaps related.

Thank you!

**Comment by kyoshino** [comment]
I just released version 2.2.5 to remove the request monitoring code introduced with 2.2, which was to retrieve page resources faster but might conflict with other add-ons like ad blockers. There was a [better way](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network/getHAR) to retieve resoureces. Let me know if this solves the issue.

**Comment by ollicle** [comment]
Hi @kyoshino,
I just updated (to 2.2.6) and I can no longer reproduce this issue. So fixed! 👏

**Comment by kyoshino** [comment]
Thank you for the testing! And, sorry for the inconvenience 🙇
