### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by rugk** [fxsitecompat/firefox-extension#3]
It spams the add-on debugging console.

https://gist.github.com/rugk/a97943b9289032435d28e234f1adb0e3

Operating system: Linux/Fedora 32
Browser: Firefox 78.0.1 (Fedora's version)

See https://github.com/keepassxreboot/keepassxc-browser/issues/933 for more details/possibly related issue.

**Comment by kyoshino** [comment]
Thanks for your report. I’m aware of the issue but don’t know why this is happening. The [relevant code](https://github.com/fxsitecompat/firefox-extension/blob/master/extension/background.js#L55-L57) is in a `try-catch` block, so the `Error` is supposed to be suppressed. I think it’s a bug in Firefox.

**Comment by rugk** [comment]
…if so… could you then please try to open a Bugzilla bug report? I don't have as much insight in your code/add-on to do it, so it would be better if you do it.

Also… empty catch blocks without any explanation are quite bad practice… hehe… :upside_down_face:

**Comment by kyoshino** [comment]
I don’t have a plan to report the issue to Bugzilla because it doesn’t affect any functionality.

**Comment by rugk** [comment]
It does. It affects me when debugging, because I cannot see my own log messages (Firefox does not really differentiate them in the log) and it's just annoying…

**Comment by kyoshino** [comment]
I have implemented a workaround, will release a new version hopefully this Sunday.

**Comment by rugk** [comment]
Thanks. :+1: :smiley:
